name: Deploy Bicep files

trigger: none
# - main

variables:
  resourceGroupName: 'rg-bicep-demo-0018'
  location: 'canadacentral'
  templateFile: '01-bicep-webapp/webapp-linux.bicep'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Create Resource Group
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)

- task: AzureCLI@2
  displayName: Validate Bicep Template
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group validate \
        --resource-group $(resourceGroupName) \
        --template-file $(templateFile)

- task: AzureCLI@2
  displayName: Deploy Bicep To Azure
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) \
        --template-file $(templateFile)
